const productList = [
    {
        id: "hp_omen_1",
        img1: "hp_omen/hp_omen_1.jpg",
        img2: "hp_omen/hp_omen_2.jpg",
        img3: "hp_omen/hp_omen_3.jpg",
        img4: "hp_omen/hp_omen_4.jpg",
        img5: "hp_omen/hp_omen_5.jpg",
        title: "Hp omen",
        description: "Descripcion pendiente, todavia no la busque",
        price: 400000,
        stock: 5,
    },
    {
        id: "asus_vivoBook_1",
        img1: "asus_vivoBook/asus_vivoBook_1.jpg",
        img2: "asus_vivoBook/asus_vivoBook_2.jpg",
        img3: "asus_vivoBook/asus_vivoBook_3.jpg",
        img4: "asus_vivoBook/asus_vivoBook_4.jpg",
        img5: "asus_vivoBook/asus_vivoBook_5.jpg",
        title: "Asus VivoBook",
        description: "Notebook Asus VivoBook E410MA azul eléctrico 14', Intel Celeron N4020  4GB de RAM 128GB SSD, Intel UHD Graphics 600 1366x768px Windows 10 Home",
        price: 97000,
        stock: 12,
    },
    {
        id: "exo_smart_1",
        img1: "exo_smart/exo_smart_1.jpg",
        img2: "exo_smart/exo_smart_2.jpg",
        img3: "exo_smart/exo_smart_3.jpg",
        img4: "exo_smart/exo_smart_4.jpg",
        img5: "exo_smart/exo_smart_5.jpg",
        title: "Exo Smart",
        description: "Notebook EXO Smart P33 gris 14.1', Intel Celeron N4020  4GB de RAM 64GB SSD, Intel UHD Graphics 600 1920x1080px Windows 11 Home",
        price: 85000,
        stock: 15,
    },
];

export default productList