const productList = [
    //pc's
    {
        id: "hp_omen_1",
        category: "pcs",
        brand: "hp",
        model: "omen 15",
        title: "Hp omen 15",
        description: "Descripción: Notebook OMEN 15-ek0062la",
        operatingSistem: "Sistema Operativo:",
        processor: "Procesador:",
        cores: "",
        ram: "Ram:",
        storage: "Memoria:",
        screen: "Pantalla:",
        graphics: "Tarjeta Grafica:",
        keyboard: "Teclado:",
        measures: "Medidas:",
        weight: "Peso:",
        drums: "Bateria y Cargador:",
        price: 400000,
        stock: 5,
        img1: "hp_omen/hp_omen_1.jpg",
        img2: "hp_omen/hp_omen_2.jpg",
        img3: "hp_omen/hp_omen_3.jpg",
        img4: "hp_omen/hp_omen_4.jpg",
        img5: "hp_omen/hp_omen_5.jpg",
    },
    {
        id: "asus_vivoBook_1",
        category: "pcs",
        brand: "asus",
        model: "vivo book",
        title: "Asus VivoBook",
        description: "Descripción: Notebook Asus VivoBook E410MA azul eléctrico 14'",
        operatingSistem: "Sistema Operativo:",
        processor: "Procesador:",
        cores: "",
        ram: "Ram:",
        storage: "Memoria:",
        screen: "Pantalla:",
        graphics: "Tarjeta Grafica:",
        keyboard: "Teclado:",
        measures: "Medidas:",
        weight: "Peso:",
        drums: "Bateria y Cargador:",
        price: 97000,
        stock: 12,
        img1: "asus_vivoBook/asus_vivoBook_1.jpg",
        img2: "asus_vivoBook/asus_vivoBook_2.jpg",
        img3: "asus_vivoBook/asus_vivoBook_3.jpg",
        img4: "asus_vivoBook/asus_vivoBook_4.jpg",
        img5: "asus_vivoBook/asus_vivoBook_5.jpg",
    },
    {
        id: "exo_smart_1",
        category: "pcs",
        brand: "exo",
        model: "smart",
        title: "Exo Smart",
        description: "Descripción: Notebook EXO Smart P33 gris 14.1'",
        operatingSistem: "Sistema Operativo:",
        processor: "Procesador:",
        cores: "",
        ram: "Ram:",
        storage: "Memoria:",
        screen: "Pantalla:",
        graphics: "Tarjeta Grafica:",
        keyboard: "Teclado:",
        measures: "Medidas:",
        weight: "Peso:",
        drums: "Bateria y Cargador:",
        price: 85000,
        stock: 15,
        img1: "exo_smart/exo_smart_1.jpg",
        img2: "exo_smart/exo_smart_2.jpg",
        img3: "exo_smart/exo_smart_3.jpg",
        img4: "exo_smart/exo_smart_4.jpg",
        img5: "exo_smart/exo_smart_5.jpg",
    },
    //smartphone's
    {
        id: "samsung_galaxy_a22_1",
        category: "smartphones",
        brand: "samsung",
        model: "galaxy a22",
        title: "Samsung Galaxy A22",
        description: "Samsung Galaxy A22 5G 128 GB white 4 GB RAM",
        operatingSistem: "Sistema Operativo:",
        processor: "Procesador:",
        cores: "",
        ram: "Ram:",
        storage: "Memoria:",
        screen: "Pantalla:",
        graphics: "Tarjeta Grafica:",
        keyboard: "Teclado:",
        measures: "Medidas:",
        weight: "Peso:",
        drums: "Bateria y Cargador:",
        price: 68999,
        stock: 20,
        img1: "samsung_galaxy_a22/samsung_galaxy_a22_1.jpg",
        img2: "samsung_galaxy_a22/samsung_galaxy_a22_2.jpg",
        img3: "samsung_galaxy_a22/samsung_galaxy_a22_3.jpg",
        img4: "samsung_galaxy_a22/samsung_galaxy_a22_4.jpg",
        img5: "samsung_galaxy_a22/samsung_galaxy_a22_5.jpg",
    },
    {
        id: "motorola_g22_1",
        category: "smartphones",
        brand: "motorola",
        model: "g22",
        title: "Motorola G22",
        description: "Moto G22 128 GB cosmic black 4 GB RAM",
        operatingSistem: "Sistema Operativo:",
        processor: "Procesador:",
        cores: "",
        ram: "Ram:",
        storage: "Memoria:",
        screen: "Pantalla:",
        graphics: "Tarjeta Grafica:",
        keyboard: "Teclado:",
        measures: "Medidas:",
        weight: "Peso:",
        drums: "Bateria y Cargador:",
        price: 41999,
        stock: 16,
        img1: "motorola_g22/motorola_g22_1.jpg",
        img2: "motorola_g22/motorola_g22_2.jpg",
        img3: "motorola_g22/motorola_g22_3.jpg",
        img4: "motorola_g22/motorola_g22_4.jpg",
        img5: "motorola_g22/motorola_g22_5.jpg",
    },
    {
        id: "motorola_g51_1",
        category: "smartphones",
        brand: "motorola",
        model: "g51",
        title: "Motorola G51",
        description: "Motorola G51 5G 128 GB azul 4 GB RAM",
        operatingSistem: "Sistema Operativo:",
        processor: "Procesador:",
        cores: "",
        ram: "Ram:",
        storage: "Memoria:",
        screen: "Pantalla:",
        graphics: "Tarjeta Grafica:",
        keyboard: "Teclado:",
        measures: "Medidas:",
        weight: "Peso:",
        drums: "Bateria y Cargador:",
        price: 62999,
        stock: 10,
        img1: "motorola_g51/motorola_g51_1.jpg",
        img2: "motorola_g51/motorola_g51_2.jpg",
        img3: "motorola_g51/motorola_g51_3.jpg",
        img4: "motorola_g51/motorola_g51_4.jpg",
        img5: "motorola_g51/motorola_g51_5.jpg",
    },
    //tablets
];

export default productList