const productList = [
    {
        id: "hp_omen_1",
        category: "pc's",
        brand: "HP",
        model: "Omen 15",
        title: "Hp omen 15",
        description: "Descripcion pendiente, todavia no la busque",
        operatingSistem: "Sistema Operativo: Windows 10 Home",
        processor: "Procesador: Intel® Core™ i7-10750H de 10.ª Generación",
        cores: "6 núcleos, 12 MB de caché",
        ram: "Ram: SDRAM DDR4-2933 de 16 GB (2 x 8 GB)",
        storage: "Memoria: SSD de 512 GB Intel®, Memoria de 32 GB Intel® Optane™",
        screen: "Pantalla: FHD de 15,6 pulgadas, 300 Hz, IPS, antirreflejante, microborde, retroiluminación WLED, 300 nits, 100% sRGB (1920 x 1080)",
        graphics: "Tarjeta Grafica: Hasta NVIDIA® GeForce® RTX 2070 SUPER™ con diseño Max-Q4",
        keyboard: "Teclado: Teclado de tamaño completo, tipo isla, retroiluminación RGB de 4 zonas, color negro sombra, con un 26-Key Rollover y tecnología Anti-Ghosting",
        measures: "Medidas: 35,78 cm (Largo) x 23,97 cm (Ancho) x 2,26 cm (Alto)",
        weight: "Peso: 2,45 kg",
        drums: "Bateria y Cargador: Batería de polímero de litio de 6 celdas, 70,9 Wh, Adaptador de CA inteligente de 200 W",
        price: "Precio: $400000",
        stock: 5,
        img1: "hp_omen/hp_omen_1.jpg",
        img2: "hp_omen/hp_omen_2.jpg",
        img3: "hp_omen/hp_omen_3.jpg",
        img4: "hp_omen/hp_omen_4.jpg",
        img5: "hp_omen/hp_omen_5.jpg",
    },
    {
        id: "asus_vivoBook_1",
        category: "pc's",
        img1: "asus_vivoBook/asus_vivoBook_1.jpg",
        img2: "asus_vivoBook/asus_vivoBook_2.jpg",
        img3: "asus_vivoBook/asus_vivoBook_3.jpg",
        img4: "asus_vivoBook/asus_vivoBook_4.jpg",
        img5: "asus_vivoBook/asus_vivoBook_5.jpg",
        title: "Asus VivoBook",
        description: "Notebook Asus VivoBook E410MA azul eléctrico 14', Intel Celeron N4020  4GB de RAM 128GB SSD, Intel UHD Graphics 600 1366x768px Windows 10 Home",
        price: "Precio: $97000",
        stock: 12,
    },
    {
        id: "exo_smart_1",
        category: "pc's",
        img1: "exo_smart/exo_smart_1.jpg",
        img2: "exo_smart/exo_smart_2.jpg",
        img3: "exo_smart/exo_smart_3.jpg",
        img4: "exo_smart/exo_smart_4.jpg",
        img5: "exo_smart/exo_smart_5.jpg",
        title: "Exo Smart",
        description: "Notebook EXO Smart P33 gris 14.1', Intel Celeron N4020  4GB de RAM 64GB SSD, Intel UHD Graphics 600 1920x1080px Windows 11 Home",
        price: "Precio: $85000",
        stock: 15,
    },
];

export default productList